name = "clarkstark"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "clark-stark-workout"
database_id = "0dca19c9-6f87-4d70-9dc7-53fe9d5d51bf"

[vars]
# Non-secret config vars
PROTEIN_TARGET = "150"
WATER_TARGET_LITERS = "3"
